version: '3'

services:
  web:
    container_name: composer
    build:
      context: .
      dockerfile: composer.dockerfile
    volumes:
      - ./app/crude:/app/crude
    ports:
      - "8000:8000"
    networks:
      - crude
    restart: always

  mysql:
    container_name: mysql
    build:
      context: .
      dockerfile: mysql.dockerfile
    ports:
      - "3307:3306"
    networks:
      - crude 
    restart: always

  phpmyadmin:
    container_name: phpmyadmin
    build:
      context: .
      dockerfile: phpmyadmin.dockerfile
    ports:
      - "8080:80"
    restart: always
    networks:
      - crude


networks:
  crude:
    driver: bridge
    
